# Generated by Django 3.2.5 on 2021-07-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Админ'), ('Leader', 'Руководство'), ('Accountant', 'Бухгалтерия'), ('Employee', 'Сотрудник')], max_length=30),
        ),
    ]
