# Generated by Django 3.2.5 on 2021-08-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Админ'), ('Leader', 'Руководство'), ('Accountant', 'Бухгалтерия'), ('Employee', 'Сотрудник'), ('Стажер', 'Стажер'), ('Учитель', 'Учитель')], max_length=30),
        ),
    ]
