# Generated by Django 3.2.5 on 2021-08-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
