# Generated by Django 3.2.5 on 2021-08-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsalary',
            name='amount',
            field=models.FloatField(),
        ),
    ]
