# Generated by Django 3.2.5 on 2021-08-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_balance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_dollar', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='debt',
            name='user',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2021-08-06'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(default='Friday', max_length=15),
        ),
    ]
