# Generated by Django 3.2.5 on 2021-08-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210806_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='one_dollar',
            field=models.IntegerField(default=1),
        ),
    ]
