# Generated by Django 3.2.5 on 2021-08-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_user_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
