# Generated by Django 3.2.5 on 2021-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_sendsalary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount_usz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='total_in_uzs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='total_in_usd',
            field=models.FloatField(blank=True, null=True),
        ),

    ]
