# Generated by Django 3.2.5 on 2021-08-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_exchangerate_one_dollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='one_dollar',
            field=models.FloatField(default=1),
        ),
    ]
