# Generated by Django 3.2.5 on 2021-08-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_attendance_is_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='standup',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
