# Generated by Django 3.2.5 on 2021-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_standup_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsalary',
            name='type',
            field=models.CharField(choices=[('Salary', 'Зарплата'), ('Prepayment', 'Аванс'), ('Fine', 'Штраф')], default='Salary', max_length=10),
        ),
    ]
