# Generated by Django 3.2.5 on 2021-08-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210806_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='total_in_uzs',
        ),
    ]
