# Generated by Django 3.2.5 on 2021-08-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_actions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
    ]
