# Generated by Django 3.2.5 on 2021-07-30 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
