# Generated by Django 3.2.5 on 2021-08-04 11:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_sendsalary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsalary',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendsalary',
            name='reason',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])]),
        ),
    ]
