# Generated by Django 3.2.5 on 2021-08-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_debt_total_in_usz'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='total_in_uzs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
