# Generated by Django 3.2.5 on 2021-07-31 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210731_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 7, 31, 9, 49, 47, 528958, tzinfo=utc)),
        ),
    ]
