# Generated by Django 3.2.5 on 2021-08-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210804_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2021-08-05'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(default='Thursday', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Админ'), ('Leader', 'Руководство'), ('Accountant', 'Бухгалтерия'), ('Employee', 'Сотрудник'), ('Стажер', 'Стажер'), ('Учитель', 'Учитель'), ('Ученик', 'Студент')], max_length=30),
        ),
    ]
