# Generated by Django 3.2.5 on 2021-08-05 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20210805_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary_type',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='salary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
