# Generated by Django 3.2.5 on 2021-08-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20210806_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
