# Generated by Django 3.2.5 on 2021-07-31 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_attendance_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
