# Generated by Django 3.2.5 on 2021-07-31 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_attendance_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='data',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
