# Generated by Django 3.2.5 on 2021-08-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20210806_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('Create_user', 'Добавление сотрудника'), ('Edit_user', 'Изменение сотрудника'), ('Add_salary', 'Добавление зарплаты'), ('Edit_salary', 'Изменение зарплаты'), ('Send_salary', 'Отправка зарплаты'), ('Send_prepayment', 'Отправка премии'), ('Send_penalty', 'Отправка штрафа'), ('Accept_salary', 'Принять зарплату'), ('Decline_salary', 'Отклонить зарплату')], max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2021-08-07'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(default='Saturday', max_length=15),
        ),
    ]
