# Generated by Django 3.2.5 on 2021-08-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_sendsalary_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsalary',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=10, null=True),
        ),
    ]
