# Generated by Django 3.2.5 on 2021-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_sendsalary_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsalary',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
