# Generated by Django 3.2.5 on 2021-07-31 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_attendance_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='data',
            field=models.DateField(default='31-07-2021'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
