# Generated by Django 3.2.5 on 2021-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_sendsalary_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_type',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='sendsalary',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Подвтвержден', 'Подвтержден'), ('Отклонен', 'Отклонен')], default='AWAITING', max_length=15),
        ),
        migrations.AlterField(
            model_name='sendsalary',
            name='type',
            field=models.CharField(choices=[('Зарплата', 'Зарплата'), ('Аванс', 'Аванс'), ('Штраф', 'Штраф')], default='Salary', max_length=10),
        ),
    ]
