# Generated by Django 3.2.5 on 2021-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20210805_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsalary',
            name='type',
            field=models.CharField(choices=[('Зарплата', 'Зарплата'), ('Аванс', 'Аванс'), ('Штраф', 'Штраф')], default='Зарплата', max_length=10),
        ),
    ]
