# Generated by Django 3.2.5 on 2021-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_sendsalary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsalary',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Подвтвержден', 'Подвтержден'), ('Отклонен', 'Отклонен')], default='AWAITING', max_length=15),
        ),
        migrations.AlterField(
            model_name='sendsalary',
            name='type',
            field=models.CharField(choices=[('Зарплата', 'Зарплата'), ('Аванс', 'Аванс'), ('Штраф', 'Штраф')], default='Salary', max_length=10),
        ),
    ]
