# Generated by Django 3.2.5 on 2021-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20210805_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsalary',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Подвтвержден', 'Подвтержден'), ('Отклонен', 'Отклонен')], default='В ожидании', max_length=15),
        ),
        migrations.AlterField(
            model_name='sendsalary',
            name='type',
            field=models.CharField(choices=[('Зарплата', 'Зарплата'), ('Аванс', 'Аванс'), ('Штраф', 'Штраф')], max_length=10),
        ),
    ]
