# Generated by Django 3.2.5 on 2021-08-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20210805_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsalary',
            name='type',
            field=models.CharField(choices=[('Salary', 'Зарплата'), ('Prepayment', 'Аванс'), ('Penalty', 'Штраф')], default='Salary', max_length=10),
        ),
    ]
