# Generated by Django 3.2.5 on 2021-07-31 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_auto_20210731_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='time', to='crm.attendance'),
        ),
    ]
