# Generated by Django 3.2.5 on 2021-07-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
