# Generated by Django 3.2.5 on 2021-08-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_auto_20210802_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
