# Generated by Django 3.2.5 on 2021-08-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_sendsalary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsalary',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'В ожидании'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен')], default='AWAITING', max_length=10),
        ),
    ]
