# Generated by Django 3.2.5 on 2021-08-02 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_alter_sendsalary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='standup',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
