# Generated by Django 3.2.5 on 2021-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_standup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standup',
            old_name='questions',
            new_name='question',
        ),
        migrations.AddField(
            model_name='standup',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
