# Generated by Django 3.2.5 on 2021-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_auto_20210802_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standup',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
