# Generated by Django 3.2.5 on 2021-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_alter_standup_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('Normal', 'Обычный'), ('Extra', 'Экстренный')], max_length=10, null=True),
        ),
    ]
