# Generated by Django 3.2.5 on 2021-08-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_alter_salary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standup',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='standup',
            name='question',
        ),
        migrations.RemoveField(
            model_name='standup',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.CharField(default='08', max_length=15),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='balance_type',
            field=models.CharField(choices=[('Sum', 'UZS'), ('Usd', 'USD')], default='Sum', max_length=3),
        ),
        migrations.AddField(
            model_name='standup',
            name='attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.attendance'),
        ),
        migrations.AddField(
            model_name='standup',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standup',
            name='q1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standup',
            name='q2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standup',
            name='q3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standup',
            name='q4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standup',
            name='q5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standup',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2021-08-03'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(default='Tuesday', max_length=15),
        ),
    ]
